// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB64f31jcENb-yM79yZrKFg9enSQrkHKGg',
    appId: '1:558639138520:web:5a193f0ec6aef6212339ad',
    messagingSenderId: '558639138520',
    projectId: 'encanto-49261',
    authDomain: 'encanto-49261.firebaseapp.com',
    storageBucket: 'encanto-49261.appspot.com',
    measurementId: 'G-2TJ5SC3D9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhOYV0UAyp6-ugduNZ5WDSiAzwqU1EsCg',
    appId: '1:558639138520:android:81abaf04d6c317112339ad',
    messagingSenderId: '558639138520',
    projectId: 'encanto-49261',
    storageBucket: 'encanto-49261.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRqXxX1MMNQO29BX-6BnG9nVr9vsMECJs',
    appId: '1:558639138520:ios:0d303e2258371f3c2339ad',
    messagingSenderId: '558639138520',
    projectId: 'encanto-49261',
    storageBucket: 'encanto-49261.appspot.com',
    iosBundleId: 'com.example.mainProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRqXxX1MMNQO29BX-6BnG9nVr9vsMECJs',
    appId: '1:558639138520:ios:de3d7ef41e47220f2339ad',
    messagingSenderId: '558639138520',
    projectId: 'encanto-49261',
    storageBucket: 'encanto-49261.appspot.com',
    iosBundleId: 'com.example.mainProject.RunnerTests',
  );
}
